image:
  repository: ghcr.io/m4dm4rtig4n/eat_scheduler
  tag: "0.1.0"

database:
  mode: sqlite
  sqlite:
    persistence:
      enabled: true
      size: 1Gi

ingress:
  enabled: true
  className: apisix
  hosts:
    - host: eat.btgroup.io
      paths:
        - path: /
          pathType: Prefix
